#!/bin/bash
# RunPod deployment helper script
# This script should be used when creating a new RunPod with this Docker image

echo "RunPod Network Volume Configuration"
echo "=================================="

# Required environment variables for RunPod network volume support
echo "Set these environment variables when creating your RunPod:"
echo ""
echo "# Required:"
echo "RUNPOD_API_KEY=your_runpod_api_key_here"
echo ""
echo "# Optional (with defaults):"
echo "RUNPOD_NETWORK_VOLUME_ID=inmf69hxr7"
echo "RUNPOD_DATA_CENTER_REGION=US-IL-1"
echo "RUNPOD_MOUNT_PATH=/network-storage"
echo ""
echo "Network Volume Details:"
echo "- Default Volume ID: inmf69hxr7"
echo "- Default Region: US-IL-1"
echo "- Default Mount Path: /network-storage"
echo ""
echo "Example RunPod creation command:"
echo "runpod create pod \\"
echo "  --name chattervosker-pod \\"
echo "  --image-name your-docker-registry/chattervoskerfaster:latest \\"
echo "  --gpu-type 'NVIDIA RTX 4090' \\"
echo "  --container-disk-size 50 \\"
echo "  --env RUNPOD_API_KEY=your_api_key_here \\"
echo "  --env RUNPOD_NETWORK_VOLUME_ID=your_volume_id \\"
echo "  --env RUNPOD_DATA_CENTER_REGION=your_region \\"
echo "  --env S3_BUCKET=your_s3_bucket \\"
echo "  --env S3_ACCESS_KEY_ID=your_s3_key \\"
echo "  --env S3_SECRET_ACCESS_KEY=your_s3_secret"
echo ""
echo "Alternative: Use RunPod web interface and set environment variables:"
echo "- RUNPOD_API_KEY: Your RunPod API key (required)"
echo "- RUNPOD_NETWORK_VOLUME_ID: Your network volume ID (optional, defaults to inmf69hxr7)"
echo "- RUNPOD_DATA_CENTER_REGION: Your data center region (optional, defaults to US-IL-1)"
echo "- RUNPOD_MOUNT_PATH: Mount path for network volume (optional, defaults to /network-storage)"
echo "- S3_BUCKET: Your S3 bucket name (optional)"
echo "- S3_ACCESS_KEY_ID: Your S3 access key (optional)"
echo "- S3_SECRET_ACCESS_KEY: Your S3 secret key (optional)"
echo ""
echo "The application will:"
echo "1. Attempt to mount your configured network volume to the specified mount path"
echo "2. Check for existing models on network storage"
echo "3. Download models to network storage if not present"
echo "4. Fall back to local storage if network storage unavailable"
echo "5. Create symlinks for efficient model access"
echo ""
echo "Network Volume Benefits:"
echo "- Models persist across pod restarts"
echo "- Faster startup times after initial download"
echo "- Shared models across multiple pods"
echo "- Reduced container disk usage"
echo ""
echo "Networking:"
echo "- Expose TCP ports 7860 (Gradio UI) and 7861 (HearsAid API) via RunPod's public networking settings"
echo "- Configure firewall rules or access lists as needed for the new API endpoint"
